"""
PPTX generation service.

Three rendering paths are supported, tried in order of preference:

  1. XML-based (preferred)
     Unpacks the template PPTX, edits each slide's XML directly, then repacks.
     Preserves 100% of template formatting (fonts, animations, SmartArt).
     Requires: scripts/office/unpack.py, scripts/add_slide.py, scripts/clean.py,
               scripts/office/pack.py  (all in PROJECT_ROOT/scripts/).
     Controlled via: PPTX_RENDERER=auto|xml

  2. Stencil-based
     Clones slides from the brand stencil template, replaces text/images while
     preserving all original formatting.  Requires:
       - A .pptx stencil file in template_padrao/local/example/
       - tools/layout_catalog.json  (generated by tools/inspect_template.py)
     Controlled via: PPTX_RENDERER=auto|stencil

  3. Programmatic (fallback)
     Draws slides from scratch using python-pptx shapes.  Always works, but
     produces a plain visual style that does not match the brand stencil.
     Controlled via: PPTX_RENDERER=auto|programmatic

Environment variable:
    PPTX_RENDERER=auto           (default) — try xml → stencil → programmatic
    PPTX_RENDERER=xml            — force XML path only (raises on failure)
    PPTX_RENDERER=stencil        — force stencil path only
    PPTX_RENDERER=programmatic   — force programmatic path only

The public entry-point is generate_pptx().
"""

import io
import logging
import os
import uuid
from dataclasses import dataclass

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE_TYPE
from pptx.oxml.ns import qn

from models.schemas import StorytellingOutline, TemplateInfo


def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    """Convert a hex color string (with or without #) to an (R, G, B) tuple."""
    hex_color = hex_color.lstrip("#")
    return (int(hex_color[0:2], 16), int(hex_color[2:4], 16), int(hex_color[4:6], 16))

logger = logging.getLogger(__name__)


@dataclass
class RenderPipelineResult:
    """Internal metadata about renderer decisions for observability/debug."""

    renderer_used: str
    fallback_chain: list[dict[str, str]]
    request_id: str


class RenderedPptxBuffer(io.BytesIO):
    """BytesIO response that carries pipeline metadata for internal consumers."""

    def __init__(self, content: bytes, metadata: RenderPipelineResult):
        super().__init__(content)
        self.metadata = metadata


def _attach_render_metadata(
    buffer: io.BytesIO,
    *,
    renderer_used: str,
    fallback_chain: list[dict[str, str]],
    request_id: str,
) -> RenderedPptxBuffer:
    """Return a BytesIO-compatible response with renderer metadata attached."""
    return RenderedPptxBuffer(
        buffer.getvalue(),
        RenderPipelineResult(
            renderer_used=renderer_used,
            fallback_chain=fallback_chain,
            request_id=request_id,
        ),
    )


# ---------------------------------------------------------------------------
# Helpers shared by programmatic drawers
# ---------------------------------------------------------------------------

def _rgb(hex_color: str) -> RGBColor:
    h = hex_color.lstrip("#")
    return RGBColor(int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def _in(inches: float) -> Emu:
    return Inches(inches)


def _add_rect(slide, left, top, width, height, fill_hex: str | None = None,
              line_hex: str | None = None, line_width_pt: float = 0):
    """Add a filled/outlined rectangle shape."""
    shape = slide.shapes.add_shape(
        1,  # MSO_SHAPE.RECTANGLE
        _in(left), _in(top), _in(width), _in(height)
    )
    if fill_hex:
        shape.fill.solid()
        shape.fill.fore_color.rgb = _rgb(fill_hex)
    else:
        shape.fill.background()

    if line_hex:
        shape.line.color.rgb = _rgb(line_hex)
        shape.line.width = Pt(line_width_pt)
    else:
        shape.line.fill.background()
    return shape


def _add_textbox(slide, left, top, width, height,
                 text: str, font_name: str, font_size_pt: float,
                 bold: bool = False, color_hex: str = "#1A1A1A",
                 align: PP_ALIGN = PP_ALIGN.LEFT,
                 wrap: bool = True, italic: bool = False) -> None:
    """Add a text box with a single paragraph/run of text."""
    txBox = slide.shapes.add_textbox(_in(left), _in(top), _in(width), _in(height))
    tf = txBox.text_frame
    tf.word_wrap = wrap
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.name = font_name
    run.font.size = Pt(font_size_pt)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = _rgb(color_hex)


def _add_bullet_list(slide, left, top, width, height,
                     points: list[str], font_name: str,
                     font_size_pt: float = 14, color_hex: str = "#1A1A1A",
                     bullet: bool = True) -> None:
    """Add a text box with multiple bullet point paragraphs."""
    txBox = slide.shapes.add_textbox(_in(left), _in(top), _in(width), _in(height))
    tf = txBox.text_frame
    tf.word_wrap = True
    for i, point in enumerate(points):
        if i == 0:
            p = tf.paragraphs[0]
        else:
            p = tf.add_paragraph()
        p.space_after = Pt(6)
        run = p.add_run()
        run.text = ("• " if bullet else "") + point
        run.font.name = font_name
        run.font.size = Pt(font_size_pt)
        run.font.color.rgb = _rgb(color_hex)


def _add_logo(slide, logo_path: str | None,
              left: float, top: float, width: float, height: float) -> None:
    """Add logo image if the file exists."""
    if logo_path and os.path.isfile(logo_path):
        slide.shapes.add_picture(logo_path, _in(left), _in(top),
                                 _in(width), _in(height))


def _add_dashed_placeholder(slide, left, top, width, height,
                             hint: str, color_hex: str, font_name: str) -> None:
    """Dashed rectangle with hint text for chart/image placeholders."""
    shape = _add_rect(slide, left, top, width, height,
                      fill_hex=None, line_hex=color_hex, line_width_pt=1.5)
    # dash style: 4 = dash
    shape.line.dash_style = 4

    tf = shape.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.CENTER
    run = p.add_run()
    run.text = hint
    run.font.name = font_name
    run.font.size = Pt(12)
    run.font.italic = True
    run.font.color.rgb = _rgb(color_hex)


# ---------------------------------------------------------------------------
# Slide-removal helper
# ---------------------------------------------------------------------------

_R_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"


def _remove_existing_slides(prs: Presentation) -> None:
    """Remove all slides from the presentation, preserving layouts."""
    try:
        while len(prs.slides._sldIdLst) > 0:
            rId = prs.slides._sldIdLst[0].get(f"{{{_R_NS}}}id")
            if rId:
                prs.part.drop_rel(rId)
            del prs.slides._sldIdLst[0]
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Slide drawers  (one per layout type)
# Each function receives an empty slide and draws everything on it.
# ---------------------------------------------------------------------------

def _draw_header_bar(slide, title: str, palette: dict, font_name: str,
                     logo_path: str | None) -> None:
    """
    Shared header: dark-blue top bar, yellow accent line, title in bar,
    logo on the right edge of the bar.
    Used by: content, two-column, chart-placeholder, image-text.
    """
    BAR_H = 0.72       # top bar height in inches
    ACCENT_H = 0.055   # yellow line thickness

    # Dark-blue bar
    _add_rect(slide, 0, 0, 13.33, BAR_H, fill_hex=palette["secondary"])

    # Yellow accent line below bar
    _add_rect(slide, 0, BAR_H, 13.33, ACCENT_H, fill_hex=palette["accent"])

    # Title in bar
    _add_textbox(slide, 0.30, 0, 11.2, BAR_H,
                 text=title, font_name=font_name, font_size_pt=22,
                 bold=True, color_hex="#FFFFFF", align=PP_ALIGN.LEFT)

    # Logo
    _add_logo(slide, logo_path, left=12.15, top=0.22, width=0.94, height=0.28)


def _draw_title_slide(slide, title: str, talking_points: list[str],
                      palette: dict, font_name: str, logo_path: str | None) -> None:
    """
    Cover / title slide.
    Left ~42% = dark-navy panel. Right side = white with optional image area.
    """
    PANEL_W = 5.60

    # White full background
    _add_rect(slide, 0, 0, 13.33, 7.50, fill_hex=palette["background"])

    # Navy left panel
    _add_rect(slide, 0, 0, PANEL_W, 7.50, fill_hex=palette["secondary"])

    # Yellow accent stripe on top of panel
    _add_rect(slide, 0, 0, PANEL_W, 0.08, fill_hex=palette["accent"])

    # Yellow accent stripe at bottom of panel
    _add_rect(slide, 0, 7.42, PANEL_W, 0.08, fill_hex=palette["accent"])

    # Blue accent line on right side of panel (thin separator)
    _add_rect(slide, PANEL_W, 0, 0.04, 7.50, fill_hex=palette["primary"])

    # Title (main) in the panel - vertically centered
    subtitle = talking_points[0] if talking_points else ""
    _add_textbox(slide, 0.40, 1.80, PANEL_W - 0.60, 2.40,
                 text=title, font_name=font_name, font_size_pt=36,
                 bold=True, color_hex="#FFFFFF", align=PP_ALIGN.LEFT)

    # Subtitle / first talking point
    if subtitle:
        _add_textbox(slide, 0.40, 4.40, PANEL_W - 0.60, 1.20,
                     text=subtitle, font_name=font_name, font_size_pt=16,
                     bold=False, color_hex="#CCE0FF", align=PP_ALIGN.LEFT)

    # Additional talking points (if any) as small items below subtitle
    extras = talking_points[1:]
    if extras:
        _add_bullet_list(slide, 0.40, 5.80, PANEL_W - 0.60, 1.40,
                         extras, font_name=font_name, font_size_pt=11,
                         color_hex="#AACCEE", bullet=True)

    # Right side: decorative placeholder area
    _add_rect(slide, PANEL_W + 0.30, 0.50, 13.33 - PANEL_W - 0.60, 6.50,
              fill_hex=None, line_hex=palette["primary"], line_width_pt=0.5)
    _add_textbox(slide, PANEL_W + 0.30, 2.80, 13.33 - PANEL_W - 0.60, 1.00,
                 text="[ imagem / gráfico ]",
                 font_name=font_name, font_size_pt=11,
                 italic=True, color_hex=palette["primary"],
                 align=PP_ALIGN.CENTER)

    # Logo top-right
    _add_logo(slide, logo_path, left=12.15, top=0.22, width=0.94, height=0.28)


def _draw_content_slide(slide, title: str, talking_points: list[str],
                        palette: dict, font_name: str, logo_path: str | None) -> None:
    """Standard content slide: header bar + bulleted body."""
    _draw_header_bar(slide, title, palette, font_name, logo_path)

    # Body area
    body_top = 0.90
    _add_bullet_list(slide, 0.40, body_top, 12.53, 6.40,
                     talking_points, font_name=font_name, font_size_pt=16,
                     color_hex=palette["text"], bullet=True)


def _draw_two_column_slide(slide, title: str, talking_points: list[str],
                           palette: dict, font_name: str, logo_path: str | None) -> None:
    """Two-column layout: header bar, thin separator, points split left/right."""
    _draw_header_bar(slide, title, palette, font_name, logo_path)

    # Split talking points between two columns
    mid = max(1, len(talking_points) // 2)
    left_pts = talking_points[:mid]
    right_pts = talking_points[mid:]

    COL_TOP = 0.95
    COL_H = 6.30
    SEP_X = 6.82

    # Column header accent bars
    _add_rect(slide, 0.30, COL_TOP, 6.22, 0.06, fill_hex=palette["primary"])
    _add_rect(slide, SEP_X + 0.30, COL_TOP, 6.02, 0.06, fill_hex=palette["primary"])

    # Thin vertical separator
    _add_rect(slide, SEP_X, COL_TOP, 0.03, COL_H, fill_hex=palette["primary"])

    # Content
    _add_bullet_list(slide, 0.30, COL_TOP + 0.18, 6.22, COL_H - 0.18,
                     left_pts, font_name=font_name, font_size_pt=14,
                     color_hex=palette["text"], bullet=True)
    _add_bullet_list(slide, SEP_X + 0.30, COL_TOP + 0.18, 6.02, COL_H - 0.18,
                     right_pts, font_name=font_name, font_size_pt=14,
                     color_hex=palette["text"], bullet=True)


def _draw_chart_placeholder_slide(slide, title: str, talking_points: list[str],
                                   palette: dict, font_name: str,
                                   logo_path: str | None,
                                   placeholder_hint: str = "") -> None:
    """Chart-placeholder layout: header bar, talking points, large dashed area."""
    _draw_header_bar(slide, title, palette, font_name, logo_path)

    # Brief talking points at top (max 3, concise)
    short_pts = talking_points[:3]
    if short_pts:
        _add_bullet_list(slide, 0.40, 0.95, 12.53, 1.30,
                         short_pts, font_name=font_name, font_size_pt=13,
                         color_hex=palette["text"], bullet=True)

    # Large dashed placeholder
    hint = placeholder_hint or "[ Inserir gráfico / tabela ]"
    _add_dashed_placeholder(slide, 0.60, 2.50, 12.13, 4.50,
                            hint=hint, color_hex=palette["primary"],
                            font_name=font_name)


def _draw_image_text_slide(slide, title: str, talking_points: list[str],
                           palette: dict, font_name: str, logo_path: str | None,
                           placeholder_hint: str = "") -> None:
    """Image-left, text-right layout."""
    _draw_header_bar(slide, title, palette, font_name, logo_path)

    IMG_W = 6.20
    TXT_X = IMG_W + 0.50
    CONTENT_TOP = 0.90

    # Left image placeholder
    _add_rect(slide, 0.30, CONTENT_TOP, IMG_W, 6.35,
              fill_hex="#EEF3FB",
              line_hex=palette["primary"], line_width_pt=0.8)
    hint = placeholder_hint or "[ Inserir imagem ]"
    _add_textbox(slide, 0.30, CONTENT_TOP + 2.80, IMG_W, 0.80,
                 text=hint, font_name=font_name, font_size_pt=12,
                 italic=True, color_hex=palette["primary"], align=PP_ALIGN.CENTER)

    # Right text content
    _add_bullet_list(slide, TXT_X, CONTENT_TOP + 0.30, 13.33 - TXT_X - 0.30, 5.80,
                     talking_points, font_name=font_name, font_size_pt=14,
                     color_hex=palette["text"], bullet=True)


def _draw_closing_slide(slide, title: str, talking_points: list[str],
                        palette: dict, font_name: str, logo_path: str | None) -> None:
    """Closing / thank-you slide: full dark-blue background, white centered title."""
    # Dark-blue full background
    _add_rect(slide, 0, 0, 13.33, 7.50, fill_hex=palette["secondary"])

    # Yellow accent bars top and bottom
    _add_rect(slide, 0, 0, 13.33, 0.12, fill_hex=palette["accent"])
    _add_rect(slide, 0, 7.38, 13.33, 0.12, fill_hex=palette["accent"])

    # Blue side accents
    _add_rect(slide, 0, 0, 0.08, 7.50, fill_hex=palette["primary"])
    _add_rect(slide, 13.25, 0, 0.08, 7.50, fill_hex=palette["primary"])

    # Large centered title
    _add_textbox(slide, 1.0, 1.80, 11.33, 2.50,
                 text=title, font_name=font_name, font_size_pt=52,
                 bold=True, color_hex="#FFFFFF", align=PP_ALIGN.CENTER)

    # Subtitle / talking points below
    if talking_points:
        _add_textbox(slide, 1.0, 4.50, 11.33, 1.80,
                     text="  •  ".join(talking_points),
                     font_name=font_name, font_size_pt=14,
                     color_hex="#CCE0FF", align=PP_ALIGN.CENTER)

    # Logo top-right
    _add_logo(slide, logo_path, left=12.15, top=0.22, width=0.94, height=0.28)


# ---------------------------------------------------------------------------
# Layout dispatcher (programmatic path)
# ---------------------------------------------------------------------------

_DRAWERS = {
    "title":             _draw_title_slide,
    "content":           _draw_content_slide,
    "two-column":        _draw_two_column_slide,
    "chart-placeholder": _draw_chart_placeholder_slide,
    "image-text":        _draw_image_text_slide,
    "closing":           _draw_closing_slide,
}


def _draw_slide(slide, slide_data, palette: dict, font_name: str,
                logo_path: str | None) -> None:
    """Dispatch to the correct drawer based on slide layout type."""
    layout = slide_data.layout
    drawer = _DRAWERS.get(layout, _draw_content_slide)

    if layout in ("chart-placeholder", "image-text"):
        drawer(slide, slide_data.title, slide_data.talking_points,
               palette, font_name, logo_path, slide_data.placeholder_hint)
    else:
        drawer(slide, slide_data.title, slide_data.talking_points,
               palette, font_name, logo_path)


# ---------------------------------------------------------------------------
# Stencil path helpers
# ---------------------------------------------------------------------------

def _find_stencil_file(template_path: str) -> str | None:
    """
    Look for any .pptx file in ../../template_padrao/local/example/ relative
    to template_path.  Returns the first match, or None.
    """
    template_dir = os.path.dirname(os.path.abspath(template_path))
    example_dir  = os.path.normpath(
        os.path.join(template_dir, "..", "..", "template_padrao", "local", "example")
    )

    if not os.path.isdir(example_dir):
        # Try one level up (template_path may already be inside backend/)
        example_dir = os.path.normpath(
            os.path.join(template_dir, "..", "..", "..", "template_padrao", "local", "example")
        )

    if not os.path.isdir(example_dir):
        logger.debug("Stencil example dir not found: %s", example_dir)
        return None

    import glob as _glob
    pptx_files = sorted(_glob.glob(os.path.join(example_dir, "*.pptx")))
    if pptx_files:
        logger.debug("Found stencil: %s", pptx_files[0])
        return pptx_files[0]

    return None


def _generate_pptx_stencil(
    outline: StorytellingOutline,
    stencil_path: str,
    catalog_path: str,
    template_meta: TemplateInfo,
) -> io.BytesIO:
    """
    Render the deck using the stencil + catalog approach.

    Imports StencilRenderer and VisualDirector lazily to avoid circular
    imports and to keep the fallback path self-contained.
    """
    import json as _json

    from services.render_from_template import StencilRenderer
    from services.visual_director import VisualDirector

    # Load catalog
    with open(catalog_path, "r", encoding="utf-8") as fh:
        catalog = _json.load(fh)

    # Locate brand_tokens.json next to layout_catalog.json
    tokens_path = os.path.join(os.path.dirname(catalog_path), "brand_tokens.json")
    if os.path.isfile(tokens_path):
        with open(tokens_path, "r", encoding="utf-8") as fh:
            brand_tokens = _json.load(fh)
    else:
        # Build a minimal brand_tokens from template_meta
        palette = template_meta.palette.model_dump()
        brand_tokens = {
            "palette":       palette,
            "typography": {
                "title":    {"font": template_meta.font_title or "Avantt", "size_pt": 28, "bold": True,  "color": palette.get("secondary", "#00328D")},
                "subtitle": {"font": template_meta.font_title or "Avantt", "size_pt": 20, "bold": True,  "color": palette.get("secondary", "#00328D")},
                "body":     {"font": template_meta.font_body  or "Avantt", "size_pt": 9,  "bold": False, "color": palette.get("text", "#00328D")},
                "kpi":      {"font": template_meta.font_title or "Avantt", "size_pt": 28, "bold": True,  "color": palette.get("accent", "#FFA41B")},
                "label":    {"font": template_meta.font_body  or "Avantt", "size_pt": 8,  "bold": False, "color": palette.get("primary", "#0766FF")},
            },
            "slide_width_in":  13.33,
            "slide_height_in": 7.5,
        }

    renderer = StencilRenderer(stencil_path, catalog, brand_tokens)

    # VisualDirector without an API key (deterministic only)
    vd = VisualDirector(catalog_path, tokens_path if os.path.isfile(tokens_path) else catalog_path)

    return renderer.render(outline, visual_director=vd)


def _generate_pptx_programmatic(
    outline: StorytellingOutline,
    template_path: str,
    template_meta: TemplateInfo,
) -> io.BytesIO:
    """
    Original programmatic renderer.

    Draws all slides from scratch using python-pptx shape primitives.
    The template file only provides the base theme/fonts.
    """
    # Open with bytes to handle paths with spaces
    try:
        with open(template_path, "rb") as fh:
            prs = Presentation(io.BytesIO(fh.read()))
    except Exception:
        prs = Presentation(template_path)

    # Ensure slide size is widescreen 16:9
    prs.slide_width  = Inches(13.33)
    prs.slide_height = Inches(7.50)

    palette   = template_meta.palette.model_dump()
    font_name = template_meta.font_title or "Avantt"

    # Logo path: sits next to the template JSON / PPTX
    template_dir = os.path.dirname(template_path)
    logo_path    = os.path.join(template_dir, "logo.png")

    _remove_existing_slides(prs)

    # Use the first available blank layout
    blank_layout = prs.slide_layouts[0]
    for layout in prs.slide_layouts:
        if "blank" in layout.name.lower() or "em branco" in layout.name.lower():
            blank_layout = layout
            break

    for slide_data in outline.slides:
        slide = prs.slides.add_slide(blank_layout)
        _draw_slide(slide, slide_data, palette, font_name, logo_path)

    buffer = io.BytesIO()
    prs.save(buffer)
    buffer.seek(0)

    if buffer.getbuffer().nbytes > 50 * 1024 * 1024:
        raise ValueError("Generated PPTX exceeds 50MB size limit")

    return buffer


# ---------------------------------------------------------------------------
# XML renderer path helper
# ---------------------------------------------------------------------------

def _generate_pptx_xml_path(
    outline: StorytellingOutline,
    template_path: str,
    template_meta: TemplateInfo,
) -> io.BytesIO:
    """
    Thin wrapper: import and call xml_renderer.generate_pptx_xml lazily.

    Raises whatever xml_renderer raises (RuntimeError, CalledProcessError).
    """
    from services.xml_renderer import generate_pptx_xml
    return generate_pptx_xml(outline, template_path, template_meta)


# ---------------------------------------------------------------------------
# Renderer selection
# ---------------------------------------------------------------------------

def _get_renderer_setting() -> str:
    """Read PPTX_RENDERER from the environment (default: auto)."""
    return os.environ.get("PPTX_RENDERER", "auto").strip().lower()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_pptx(
    outline: StorytellingOutline,
    template_path: str,
    template_meta: TemplateInfo,
    request_id: str | None = None,
) -> io.BytesIO:
    """
    Generate a PPTX from the storytelling outline.

    Rendering strategy (controlled by PPTX_RENDERER env var):

      auto (default): xml → stencil → programmatic  (fallback on exception)
      xml:            XML-based only (raises on failure — no fallback)
      stencil:        stencil only
      programmatic:   programmatic only

    Parameters
    ----------
    outline : StorytellingOutline
        The structured slide outline to render.
    template_path : str
        Path to the base template .pptx.
    template_meta : TemplateInfo
        Palette, font, and layout metadata for the template.

    Returns
    -------
    io.BytesIO
        In-memory PPTX buffer, seeked to position 0.
    """
    request_id = request_id or str(uuid.uuid4())
    renderer = _get_renderer_setting()
    fallback_chain: list[dict[str, str]] = []

    logger.info(
        "Starting PPTX generation pipeline",
        extra={"request_id": request_id, "renderer_preference": renderer},
    )

    # --- Resolve stencil + catalog paths (shared by auto and stencil modes) ---
    stencil_path = _find_stencil_file(template_path)
    template_dir = os.path.dirname(os.path.abspath(template_path))
    catalog_path = os.path.normpath(
        os.path.join(template_dir, "..", "..", "tools", "layout_catalog.json")
    )
    if not os.path.isfile(catalog_path):
        catalog_path = os.path.normpath(
            os.path.join(template_dir, "..", "..", "..", "tools", "layout_catalog.json")
        )

    # -----------------------------------------------------------------------
    # Forced single-renderer modes
    # -----------------------------------------------------------------------
    if renderer == "xml":
        logger.info(
            "Using forced renderer",
            extra={"request_id": request_id, "renderer_used": "xml", "fallback_chain": fallback_chain},
        )
        buf = _generate_pptx_xml_path(outline, template_path, template_meta)
        return _attach_render_metadata(
            buf,
            renderer_used="xml",
            fallback_chain=fallback_chain,
            request_id=request_id,
        )

    if renderer == "stencil":
        logger.info(
            "Using forced renderer",
            extra={"request_id": request_id, "renderer_used": "stencil", "fallback_chain": fallback_chain},
        )
        if not stencil_path or not os.path.isfile(catalog_path):
            raise RuntimeError(
                "PPTX_RENDERER=stencil but stencil file or catalog not found."
            )
        buf = _generate_pptx_stencil(outline, stencil_path, catalog_path, template_meta)
        return _attach_render_metadata(
            buf,
            renderer_used="stencil",
            fallback_chain=fallback_chain,
            request_id=request_id,
        )

    if renderer == "programmatic":
        logger.info(
            "Using forced renderer",
            extra={"request_id": request_id, "renderer_used": "programmatic", "fallback_chain": fallback_chain},
        )
        buf = _generate_pptx_programmatic(outline, template_path, template_meta)
        return _attach_render_metadata(
            buf,
            renderer_used="programmatic",
            fallback_chain=fallback_chain,
            request_id=request_id,
        )

    # -----------------------------------------------------------------------
    # Auto mode: xml → stencil → programmatic
    # -----------------------------------------------------------------------

    # --- 1. XML-based (new preferred path) ---
    try:
        logger.info("Trying renderer", extra={"request_id": request_id, "renderer_candidate": "xml"})
        buf = _generate_pptx_xml_path(outline, template_path, template_meta)
        if buf.getbuffer().nbytes > 50 * 1024 * 1024:
            raise ValueError("Generated PPTX exceeds 50 MB size limit")
        logger.info(
            "Renderer selected",
            extra={"request_id": request_id, "renderer_used": "xml", "fallback_chain": fallback_chain},
        )
        return _attach_render_metadata(
            buf,
            renderer_used="xml",
            fallback_chain=fallback_chain,
            request_id=request_id,
        )
    except Exception as exc:
        fallback_reason = f"xml_failed:{exc.__class__.__name__}:{exc}"
        fallback_chain.append({"from": "xml", "to": "stencil", "reason": fallback_reason})
        logger.warning(
            "Renderer fallback triggered",
            extra={
                "request_id": request_id,
                "fallback_from": "xml",
                "fallback_to": "stencil",
                "fallback_reason": fallback_reason,
                "fallback_chain": fallback_chain,
            },
            exc_info=True,
        )

    # --- 2. Stencil-based ---
    if stencil_path and os.path.isfile(catalog_path):
        try:
            logger.info(
                "Trying renderer",
                extra={"request_id": request_id, "renderer_candidate": "stencil", "stencil_path": stencil_path},
            )
            buf = _generate_pptx_stencil(outline, stencil_path, catalog_path, template_meta)
            if buf.getbuffer().nbytes > 50 * 1024 * 1024:
                raise ValueError("Generated PPTX exceeds 50 MB size limit")
            logger.info(
                "Renderer selected",
                extra={"request_id": request_id, "renderer_used": "stencil", "fallback_chain": fallback_chain},
            )
            return _attach_render_metadata(
                buf,
                renderer_used="stencil",
                fallback_chain=fallback_chain,
                request_id=request_id,
            )
        except Exception as exc:
            fallback_reason = f"stencil_failed:{exc.__class__.__name__}:{exc}"
            fallback_chain.append({"from": "stencil", "to": "programmatic", "reason": fallback_reason})
            logger.warning(
                "Renderer fallback triggered",
                extra={
                    "request_id": request_id,
                    "fallback_from": "stencil",
                    "fallback_to": "programmatic",
                    "fallback_reason": fallback_reason,
                    "fallback_chain": fallback_chain,
                },
                exc_info=True,
            )
    else:
        fallback_reason = (
            f"stencil_unavailable:stencil_exists={bool(stencil_path)}:catalog_exists={os.path.isfile(catalog_path)}"
        )
        fallback_chain.append({"from": "stencil", "to": "programmatic", "reason": fallback_reason})
        logger.debug(
            "Renderer fallback triggered",
            extra={
                "request_id": request_id,
                "fallback_from": "stencil",
                "fallback_to": "programmatic",
                "fallback_reason": fallback_reason,
                "fallback_chain": fallback_chain,
                "stencil_path": stencil_path,
                "catalog_exists": os.path.isfile(catalog_path),
            },
        )

    # --- 3. Programmatic (always works) ---
    logger.info(
        "Renderer selected",
        extra={"request_id": request_id, "renderer_used": "programmatic", "fallback_chain": fallback_chain},
    )
    buf = _generate_pptx_programmatic(outline, template_path, template_meta)
    return _attach_render_metadata(
        buf,
        renderer_used="programmatic",
        fallback_chain=fallback_chain,
        request_id=request_id,
    )
