"""Tests for pptx_service — PPTX generation, slide count, titles, placeholders."""

import io
from pathlib import Path
from unittest.mock import patch

import pytest
from pptx import Presentation as PptxPresentation


def _make_blank_pptx(path: Path):
    """Create a minimal blank .pptx template file for testing."""
    prs = PptxPresentation()
    prs.save(str(path))
    return path


@pytest.fixture
def pptx_template(tmp_path):
    """Create a minimal PPTX template file."""
    pptx_path = tmp_path / "test-template.pptx"
    _make_blank_pptx(pptx_path)
    return pptx_path


def test_generated_pptx_is_valid_file(sample_outline_model, sample_template_meta, pptx_template):
    """Generated bytes must be openable as a valid PPTX."""
    from services.pptx_service import generate_pptx

    buffer = generate_pptx(sample_outline_model, str(pptx_template), sample_template_meta)
    assert isinstance(buffer, io.BytesIO)

    # Must be openable as a valid PPTX
    prs = PptxPresentation(buffer)
    assert prs is not None


def test_generated_pptx_has_correct_slide_count(sample_outline_model, sample_template_meta, pptx_template):
    """Slide count in PPTX must match total_slides in outline."""
    from services.pptx_service import generate_pptx

    buffer = generate_pptx(sample_outline_model, str(pptx_template), sample_template_meta)
    prs = PptxPresentation(buffer)
    assert len(prs.slides) == sample_outline_model.total_slides


def test_slide_titles_match_outline(sample_outline_model, sample_template_meta, pptx_template):
    """Each slide's title text must match the outline title."""
    from services.pptx_service import generate_pptx

    buffer = generate_pptx(sample_outline_model, str(pptx_template), sample_template_meta)
    prs = PptxPresentation(buffer)

    for i, slide in enumerate(prs.slides):
        expected_title = sample_outline_model.slides[i].title
        if slide.shapes.title:
            assert slide.shapes.title.text == expected_title


def test_placeholder_slide_has_shape(sample_outline_model, sample_template_meta, pptx_template):
    """Slides with has_placeholder=True must contain a rectangular shape with hint text."""
    from services.pptx_service import generate_pptx

    buffer = generate_pptx(sample_outline_model, str(pptx_template), sample_template_meta)
    prs = PptxPresentation(buffer)

    # Slide at index 2 has has_placeholder=True
    placeholder_slide = prs.slides[2]
    # Should have more shapes than a non-placeholder slide
    # Check that at least one shape contains the hint text
    hint_found = False
    for shape in placeholder_slide.shapes:
        if shape.has_text_frame:
            for paragraph in shape.text_frame.paragraphs:
                if "Bar chart: quarterly growth" in paragraph.text:
                    hint_found = True
                    break
    assert hint_found, "Placeholder hint text not found in slide shapes"


def test_generated_pptx_size_is_reasonable(sample_outline_model, sample_template_meta, pptx_template):
    """Generated PPTX should be under 50MB (the service limit)."""
    from services.pptx_service import generate_pptx

    buffer = generate_pptx(sample_outline_model, str(pptx_template), sample_template_meta)
    size = buffer.getbuffer().nbytes
    assert size < 50 * 1024 * 1024
    # Also should be non-trivially sized (at least a few KB)
    assert size > 1000


def test_hex_to_rgb_converts_correctly():
    """_hex_to_rgb should correctly convert hex color strings."""
    from services.pptx_service import _hex_to_rgb

    rgb = _hex_to_rgb("#003087")
    assert rgb[0] == 0x00
    assert rgb[1] == 0x30
    assert rgb[2] == 0x87


def test_hex_to_rgb_handles_no_hash():
    """_hex_to_rgb should handle hex strings without # prefix."""
    from services.pptx_service import _hex_to_rgb

    rgb = _hex_to_rgb("FF0000")
    assert rgb[0] == 0xFF
    assert rgb[1] == 0x00
    assert rgb[2] == 0x00


# ---------------------------------------------------------------------------
# Renderer-path regression tests (new: xml → stencil → programmatic order)
# ---------------------------------------------------------------------------

def test_generate_pptx_renderer_env_programmatic(
    sample_outline_model, sample_template_meta, pptx_template, monkeypatch
):
    """PPTX_RENDERER=programmatic must use the programmatic path exclusively.

    We verify this by patching the XML and stencil helpers and confirming they
    are never called when the env var forces 'programmatic'.
    """
    # Arrange
    monkeypatch.setenv("PPTX_RENDERER", "programmatic")

    from services.pptx_service import generate_pptx

    xml_called = []
    stencil_called = []

    with patch(
        "services.pptx_service._generate_pptx_xml_path",
        side_effect=lambda *a, **kw: xml_called.append(True),
    ), patch(
        "services.pptx_service._generate_pptx_stencil",
        side_effect=lambda *a, **kw: stencil_called.append(True),
    ):
        # Act
        buffer = generate_pptx(sample_outline_model, str(pptx_template), sample_template_meta)

    # Assert
    assert isinstance(buffer, io.BytesIO), "Result must be io.BytesIO"
    assert not xml_called, "XML renderer must NOT be called when PPTX_RENDERER=programmatic"
    assert not stencil_called, "Stencil renderer must NOT be called when PPTX_RENDERER=programmatic"


def test_generate_pptx_renderer_env_auto_fallback(
    sample_outline_model, sample_template_meta, pptx_template, monkeypatch
):
    """PPTX_RENDERER=auto must fall back to programmatic when XML renderer fails.

    We simulate a broken XML renderer and verify the service still returns a
    valid PPTX using the programmatic fallback path.
    """
    # Arrange
    monkeypatch.setenv("PPTX_RENDERER", "auto")

    from services.pptx_service import generate_pptx

    def _raise_xml(*args, **kwargs):
        raise RuntimeError("Simulated XML renderer failure")

    with patch("services.pptx_service._generate_pptx_xml_path", side_effect=_raise_xml):
        # Act — should NOT raise; programmatic path must take over
        buffer = generate_pptx(sample_outline_model, str(pptx_template), sample_template_meta)

    # Assert
    assert isinstance(buffer, io.BytesIO), "Fallback must return io.BytesIO"
    prs = PptxPresentation(buffer)
    assert len(prs.slides) == sample_outline_model.total_slides, (
        "Programmatic fallback must produce correct slide count"
    )


def test_generate_pptx_renderer_auto_succeeds(
    sample_outline_model, sample_template_meta, pptx_template, monkeypatch
):
    """PPTX_RENDERER=auto with a functioning XML renderer must return a valid BytesIO.

    We mock the XML renderer to return a programmatically generated PPTX so the
    test is self-contained and does not require real scripts on PATH.
    """
    # Arrange
    monkeypatch.setenv("PPTX_RENDERER", "auto")

    from services.pptx_service import generate_pptx, _generate_pptx_programmatic

    def _fake_xml(outline, template_path, template_meta):
        # Return a valid programmatic PPTX to simulate XML renderer success
        return _generate_pptx_programmatic(outline, template_path, template_meta)

    with patch("services.pptx_service._generate_pptx_xml_path", side_effect=_fake_xml):
        # Act
        buffer = generate_pptx(sample_outline_model, str(pptx_template), sample_template_meta)

    # Assert
    assert isinstance(buffer, io.BytesIO), "Auto mode must return io.BytesIO"
    assert buffer.getbuffer().nbytes > 0, "Buffer must not be empty"
    prs = PptxPresentation(buffer)
    assert len(prs.slides) == sample_outline_model.total_slides



def test_replace_slide_content_keeps_label_unchanged_by_default(monkeypatch):
    """Stencil flow must preserve decorative LABEL zones unless explicitly writable."""
    from services.render_from_template import StencilRenderer
    from models.schemas import SlideOutline

    class _TF:
        def __init__(self, text):
            self.text = text

    class _Shape:
        def __init__(self, text):
            self.text_frame = _TF(text)

    label_shape = _Shape("01")
    title_shape = _Shape("Template title")

    zones = [
        {"shape": label_shape, "role": "LABEL"},
        {"shape": title_shape, "role": "TITLE"},
    ]

    monkeypatch.setattr("services.render_from_template.classify_text_zones", lambda slide: zones)

    writes = []

    def _fake_replace_text(tf, new_text, max_chars=500):
        writes.append(new_text)
        tf.text = new_text

    monkeypatch.setattr("services.render_from_template.replace_text_preserving_format", _fake_replace_text)

    renderer = StencilRenderer("dummy.pptx", {"catalog": []}, {})
    slide_data = SlideOutline(
        index=0,
        layout="content",
        title="Updated title",
        talking_points=["First point", "Second point"],
        has_placeholder=False,
        placeholder_hint="",
    )

    renderer._replace_slide_content(slide=object(), slide_data=slide_data, layout_entry=None)

    assert label_shape.text_frame.text == "01"
    assert title_shape.text_frame.text == "Updated title"
    assert "First point" not in writes


def test_replace_slide_content_keeps_highlight_unchanged(monkeypatch):
    """HIGHLIGHT zones are decorative in default stencil replacement."""
    from services.render_from_template import StencilRenderer
    from models.schemas import SlideOutline

    class _TF:
        def __init__(self, text):
            self.text = text

    class _Shape:
        def __init__(self, text):
            self.text_frame = _TF(text)

    highlight_shape = _Shape("99%")
    title_shape = _Shape("Template title")
    zones = [
        {"shape": highlight_shape, "role": "HIGHLIGHT"},
        {"shape": title_shape, "role": "TITLE"},
    ]

    monkeypatch.setattr("services.render_from_template.classify_text_zones", lambda slide: zones)

    writes = []

    def _fake_replace_text(tf, new_text, max_chars=500):
        writes.append(new_text)
        tf.text = new_text

    monkeypatch.setattr("services.render_from_template.replace_text_preserving_format", _fake_replace_text)

    renderer = StencilRenderer("dummy.pptx", {"catalog": []}, {})
    slide_data = SlideOutline(
        index=0,
        layout="content",
        title="Updated title",
        talking_points=["Volume +12%", "Second point"],
        has_placeholder=False,
        placeholder_hint="",
    )

    renderer._replace_slide_content(slide=object(), slide_data=slide_data, layout_entry=None)

    assert highlight_shape.text_frame.text == "99%"
    assert title_shape.text_frame.text == "Updated title"
    assert "+12%" not in writes
